### Get all dogs

GET http://localhost:3000

### Create a new dog

POST http://localhost:3000 
content-type: application/json

{
  "name": "Folti",
  "age":1
}

### Get a dog by ID

GET http://localhost:3000/52592fba-e1d5-4207-8540-e399a9997379